default['centos']['command.execute.path'] = '/tmp/'
default['aws']['s3.bucket.name'] = 'my.project.builds'
default['aws']['s3.object.name'] = 'test.sh'
default['aws']['file.download.path'] = '/tmp/'
default['aws']['aws.s3.region'] = 'us-east-1'
